---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'RDS instance- MySql'

Resources:
  MediawikiDbsgGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue "eks-network::VPC"
      GroupDescription: Enable HTTP access via user defined port
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 3306
        IpProtocol: tcp
        ToPort: 3306

  MediawikiDb:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '20'
      AutoMinorVersionUpgrade: true
      AllowMajorVersionUpgrade: false
      BackupRetentionPeriod: 7
      CopyTagsToSnapshot: true
      DeletionProtection: true
      PubliclyAccessible: true
      DBName: 'authentication'
      DBInstanceIdentifier: 'wikidatabase'
      DBInstanceClass: 'db.t2.micro'
      Engine: 'MySQL'
      EngineVersion: '5.7.22'
      MasterUsername: 'wiki'
      MasterUserPassword: 'mediawiki'
      MultiAZ: 'true'
      PreferredBackupWindow: "05:00-06:00"
      PreferredMaintenanceWindow: "SUN:06:05-SUN:07:05"
      StorageEncrypted: true
      StorageType: gp2
      VPCSecurityGroups: !Ref MediawikiDbsgGroup

Outputs:
  MediawikiDb:
    Description: DB server name
    Value: !Ref MediawikiDb
    Export:
      Name: !Sub ${AWS::StackName}::MediawikiDb